# use rolling window version of costmap, as local costmap is not static
rolling_window: true
static_map: false
publish_frequency: 10.0
update_frequency: 10.0
combination_method: 1

width: 5.0
height: 5.0
resolution: 0.05
global_frame: odom

plugins:
 - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
 - {name: inflater, type: "costmap_2d::InflationLayer"}


obstacles:
    observation_sources: /pedsim/obstacle_cloud_local #/pedsim/people_cloud_local
    /pedsim/obstacle_cloud_local: {data_type: PointCloud, sensor_frame: base_footprint, marking: true, clearing: true, obstacle_range: 4, raytrace_range: 4, map_type: costmap}
    /pedsim/people_cloud_local: {data_type: PointCloud, sensor_frame: base_footprint, marking: true, clearing: true, obstacle_range: 4, raytrace_range: 4, map_type: costmap}

inflater:
    observation_sources: /pedsim/obstacle_cloud_local #/pedsim/people_cloud_local
    /pedsim/obstacle_cloud_local: {data_type: PointCloud, sensor_frame: base_footprint, marking: true, clearing: true, obstacle_range: 4, raytrace_range: 4}
    /pedsim/people_cloud_local: {data_type: PointCloud, sensor_frame: base_footprint, marking: true, clearing: true, obstacle_range: 4, raytrace_range: 4}

social_compliance:
    goal_topic: /move_base_simple/goal
    people_topic: /spencer/perception/tracked_persons_filtered_by_distance
    groups_topic: /spencer/perception/tracked_groups
